---
cloudsync_run:
  name: Cloudsync Run
  description: Start a Clousync Job
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            integration: truenas
            device_class: cloudsync

dataset_snapshot:
  name: Dataset Snapshot
  description: Create a Dataset Snapshot
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            integration: truenas
            device_class: datasets

service_reload:
  name: Service Reload
  description: Reload a Truenas service
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            integration: truenas
            device_class: services
